mypage/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('form/',  views.form_view, name='form_view'),
    path('list/', views.list_view, name='list_view'),
    path('edit/<int:list_id>/', views.delete_view, name='delete_view'),
    path('view/<int:view_id>/', views.todo_view, name='todo_view')
]

todo/models.py
from django.db import models


# Create your models here.
class List(models.Model):
    name = models.CharField(max_length=20)
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=1000)

    def __str__(self):
        return self.name

todo/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import List
from .form import NewForm


# Create your views here.
def index(request):
    return render(request, 'index.html')


def form_view(request):
    if request.method == 'POST':
        form = NewForm(request.POST)
        if form.is_valid():
            new_todo = List(name=form.cleaned_data['name'],
                            title=form.cleaned_data['title'],
                            content=form.cleaned_data['content'])
            new_todo.save()
            messages.success(request, "Added successfully")
            return redirect('todo:list_view')

        messages.warning(request, "Error")
    new_form = NewForm()
    template = 'form.html'
    return render(request, template_name=template, context={"form": new_form})


def list_view(request):
    template = 'list.html'
    return render(request, template_name=template, context={'all_items': List.objects.all()})


def delete_view(request, list_id):
    item = List.objects.get(pk=list_id)
    item.delete()
    messages.success(request, "Deleted successfully")
    return redirect('todo:list_view')


def todo_view(request, view_id):
    item = List.objects.get(pk=view_id)
    template = 'view.html'
    return render(request, template_name=template, context={"item": item})

todo/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>Chris's Page!</title>


<style>

  .carousel-item {
  height: 65vh;
  min-height: 350px;
  background: no-repeat center center scroll;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}

<!--form css-->


.my-input{
box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
cursor: text;
padding: 8px 10px;
transition: border .1s linear;
}
.header-title{
margin: 5rem 0;
}
h1{
font-size: 31px;
line-height: 40px;
font-weight: 600;
color:#4c5357;
}
h2{
color: #5e8396;
font-size: 21px;
line-height: 32px;
font-weight: 400;
}
.login-or {
position: relative;
color: #aaa;
margin-top: 10px;
margin-bottom: 10px;
padding-top: 10px;
padding-bottom: 10px;
}
.span-or {
display: block;
position: absolute;
left: 50%;
top: -2px;
margin-left: -25px;
background-color: #fff;
width: 50px;
text-align: center;
}
.hr-or {
height: 1px;
margin-top: 0px !important;
margin-bottom: 0px !important;
}
@media screen and (max-width:480px){
h1{
font-size: 26px;
}
h2{
font-size: 20px;
}
}
    </style>
  </head>
  <body>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'todo:index' %}">To-Do List</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Select Option
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'todo:form_view' %}">Add Item</a>
          <a class="dropdown-item" href="{% url 'todo:list_view' %}">View List</a>

        </div>
      </li>
    </ul>

  </div>
</nav>
<br><br>
  {% block messages %}
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                  <div class="text-center font-weight-bold alert alert-dismissible fade show
                       {% if message.level_tag == 'error' %}
                       alert-danger
                       {% else %}
                       alert-{{ message.tags }}
                       {% endif %}">
                    {{ message }}
                     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                     </button>
                  </div>
                {% endfor %}
              {% endif %}
        </div>
    </div>
  {% endblock messages %}

    {% block content %}

    {% endblock content %}



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

todo/templates/form.html
{% extends 'base.html' %}


{% block content %}


 <div class="container">
      <div class="col-md-6 mx-auto text-center">
         <div class="header-title">
            <h2 class="wv-heading--subtitle">
               To add a task, fill out the fields below ...-
            </h2>
         </div>
      </div>
      <div class="row">
         <div class="col-md-4 mx-auto">
            <div class="myform form ">
               <form action= "{% url 'todo:form_view' %}"  method="POST">
                   {% csrf_token %}
                  <div class="mb-2">
                     {{form.name}}
                  </div>
                  <div class="mb-2">
                     {{form.title}}
                  </div>
                  <div class="mb-2">
                     {{form.content}}
                  </div>
<!--                  <div class="form-group">-->
<!--                     <input type="text" name="name"  class="form-control my-input" id="name" placeholder="Name">-->
<!--                  </div>-->
<!--                  <div class="form-group">-->
<!--                     <input type="text" name="title"  class="form-control my-input" id="title" placeholder="Title">-->
<!--                  </div>-->
<!--                  <div class="form-group">-->
<!--                     <input type="text" name="content" id="content"  class="form-control my-input" placeholder="Content">-->
<!--                  </div>-->
                  <div class="text-center ">
                     <button type="submit" class="btn btn-primary btn-lg btn-block">Add a task to your ToDo List</button>
                  </div>
                  <div class="col-md-12 ">
                     <div class="login-or">
                        <hr class="hr-or">
                        <span class="span-or">or</span>
                     </div>
                  </div>
                  <div class="form-group">
                     <a class="btn btn-secondary btn-lg btn-block" href="{% url 'todo:list_view' %}">
                     View Your ToDo List
                     </a>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>

{% endblock content %}

todo/templates/index.html
{% extends 'base.html' %}

{% block content%}
 <header>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <!-- Slide One - Set the background image for this slide in the line below -->
      <div class="carousel-item active" style="background-image: url('https://source.unsplash.com/T86bARnzPBQ/1920x1080')">
        <div class="carousel-caption d-none d-md-block">
          <h3 class="display-4">Hi there! Welcome</h3>
          <p class="lead">My ToDo List.</p>
        </div>
      </div>
      <!-- Slide Two - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: url('https://source.unsplash.com/vhy5VkrUjME/1920x1080')">
        <div class="carousel-caption d-none d-md-block">
<!--          <h3 class="display-4">Second Slide</h3>-->
<!--          <p class="lead">This is a description for the second slide.</p>-->
        </div>
      </div>
      <!-- Slide Three - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: url('https://source.unsplash.com/collection/190727/1600x900)">
        <div class="carousel-caption d-none d-md-block">
<!--          <h3 class="display-4">Third Slide</h3>-->
<!--          <p class="lead">This is a description for the third slide.</p>-->
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
  </div>
</header>



<section class="py-5">
  <div class="container">
    <h1 class="font-weight-light">My ToDo List</h1>
    <p class="lead">One Task at a Time!</p>
  </div>
</section>
{% endblock content %}

todo/templates/list.html
{% extends 'base.html' %}

{% block content %}

<center>
    <br>
<table class="table table-bordered">
    <thead class="thead-light">
    <tr>
<!--      <th scope="col">#</th>-->
      <th class="text-center" scope="col">Name</th>
<!--      <th class="text-center" scope="col">Title</th>-->
      <th class="text-center" scope="col">Content</th>
    </tr>
    </thead>
    <tbody>
    {% if all_items %}

        {% for things in all_items %}

       <tr>
           <td><center>{{things.name}}</center></td>
<!--           <td>{{things.title}}</td>-->
<!--           <td>{{things.content}}</td>-->
<!--           <td><center><a href="{% url 'todo:delete_view' things.id %}">DELETE</a></center></td>-->
<!--           <td><center><a href="{% url 'todo:todo_view' things.id %}">VIEW</a></center></td>-->

          <td><center><a href="{% url 'todo:delete_view' things.id %}">
              <button type="button"
                  class="btn btn-danger btn-rounded btn-sm my-0">Remove</button>
           </a>
           <a href="{% url 'todo:todo_view' things.id %}">
               <button type="button"
                  class="btn btn-secondary btn-sm">View</button>
           </a></center></td>
       </tr>
    {% endfor %}
    </tbody>
    </table>
{% endif %}


    </center>

{% endblock %}

todo/templates/view.html
{% extends 'base.html' %}

 {% block content %}
<p>
<h3>Name: {{ item.name}}</h3>
</p>
<p>
<h3>Title: {{ item.title}}</h3>
</p>
<p>
<h3>Description: {{ item.content }}</h3>
</p>
        {% endblock content %}